---
# README FIRST
# 1. Subscribe to https://github.com/ansible-collections/news-for-maintainers
#    (click the Watch button on the homepage > Custom > Issues)
#    and keep this matrix up to date in accordance to related announcements.
#    Timely add new ansible-core versions and consider dropping support
#    and testing against its EOL versions.
# 2. If your collection repository is under the ansible-collections org,
#    please keep in mind that the number of GHA jobs is limited
#    and shared across all the collections in the org.
#    So, focusing on good test coverage of your collection,
#    please avoid testing against unnecessary entities such as
#    ansible-core EOL versions your collection does not support
#    or ansible-core versions that are not EOL yet but not supported by the collection.
# 3. If you don't have unit or integration tests, remove corresponding sections.
# 4. If your collection depends on other collections ensure they are installed,
#    add them to the "test-deps" input.
# 5. For the comprehensive list of the inputs supported by the
#    ansible-community/ansible-test-gh-action GitHub Action, see
#    https://github.com/marketplace/actions/ansible-test.
# 6. If you want to prevent merging PRs that do not pass all tests,
#    make sure to add the "check" job to your repository branch
#    protection once this workflow is added.
#    It is also possible to tweak which jobs are allowed to fail. See
#    https://github.com/marketplace/actions/alls-green#gotchas for more detail.
# 7. If you need help please ask in #community:ansible.com on Matrix
#    or in bridged #ansible-community on the Libera.Chat IRC channel.
#    See https://docs.ansible.com/ansible/devel/community/communication.html
#    for details.
# 8. If your collection is [going to get] included in the Ansible package,
#    it has to adhere to Python compatibility and CI testing requirements described in
#    https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html.

name: Ansible Test
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - stable-*
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still
  # testing against latest version of ansible-test for each ansible-core
  # version
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: >-
    ${{ github.workflow }}-${{
      github.event.pull_request.number || github.sha
    }}
  cancel-in-progress: true

jobs:
  ###
  # Integration tests (RECOMMENDED)
  #
  # https://docs.ansible.com/ansible/latest/dev_guide/testing_integration.html

  # If the application you are testing is available as a docker container and you want to test
  # multiple versions see the following for an example:
  # https://github.com/ansible-collections/community.zabbix/tree/master/.github/workflows

  integration:
    runs-on: [self-hosted]

    name: I (â’¶${{ matrix.ansible }}+py${{ matrix.python }})
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        ansible:
          - devel
        # - milestone
        include:
          # Add new versions announced in
          # https://github.com/ansible-collections/news-for-maintainers in a timely manner,
          # consider dropping testing against EOL versions and versions you don't support.
          # ansible-core 2.16
          - ansible: stable-2.16
          - ansible: stable-2.17
          - ansible: stable-2.18
          - ansible: stable-2.19
    steps:
      - name: >-
          Perform integration testing against
          Ansible version ${{ matrix.ansible }}
          under Python ${{ matrix.python }}
        # See the documentation for the following GitHub action on
        # https://github.com/ansible-community/ansible-test-gh-action/blob/main/README.md
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          # OPTIONAL command to run before invoking `ansible-test integration`
          pre-test-cmd: >-
            make tests/integration/inventory.winrm &&
            make install-integration-reqs ANSIBLE_COLLECTIONS_PATH="${{ github.workspace }}"

          target-python-version: ${{ matrix.python }}
          testing-type: windows-integration
          # Uncomment to configure a codecov token.
          # Check here whether a token is required: https://docs.codecov.com/docs/codecov-tokens
          # Collections in the github.com/ansible-collections/ namespace usually do not need a token.
          # codecov-token: ${{ secrets.CODECOV_TOKEN }}
          # OPTIONAL If your integration tests require code
          # from other collections, install them like this
          # test-deps: ansible.netcommon
          # OPTIONAL If set to true, will test only against changed files,
          # which should improve CI performance. See limitations on
          # https://github.com/ansible-community/ansible-test-gh-action#pull-request-change-detection
          pull-request-change-detection: false
        env:
          MECM_HOSTNAME: ${{ secrets.MECM_HOSTNAME }}
          MECM_USERNAME: ${{ secrets.MECM_USERNAME }}
          MECM_PASSWORD: ${{ secrets.MECM_PASSWORD }}

  check: # This job does nothing and is only used for the branch protection
    # or multi-stage CI jobs, like making sure that all tests pass before
    # a publishing job is started.
    if: always()

    needs:
      - integration

    runs-on: ubuntu-latest

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
